### ISSUE TITLE
Connections during slave/relay_reset do not trigger disconnect events.

### ISSUE THREAD

**Issue by nickdtodd** [karlheyes/icecast-kh#127]
Hi,

We're running `Icecast 2.4.0-kh2-17-g6320aa9` in production right now.

Here is a sample of the error log which is causing the problems: http://nopaste.linux-dev.org/?890098

It appears that during the slave/relay_reset phase, if listeners try to connect, the `listener_connected` event is fired but there isn't an associated `listener_disconnect` event to go with it meaning that we end up with numerous orphaned connected listeners in the stats.

To be honest, I'm not entirely sure that it is so much listeners connecting during this period or existing connections trying to reconnect.

From my experience it tends to be one ip address that gets logged. I mean, it's not always the same ip address each time, but when this does happen the multiple events are always from the same ip. I hope that makes sense!

It might be 123.123.123.123 x 10 (on one occasion)
Or 111.111.111.111 x 43 on another occasion.

Some mount points tend to be more affected than others but that might just be us noticing them more.

I didn't implement our deployment of Icecast so I'm trying to get an understanding of it bit by bit. If you need further information then let me know and I'll do my best to get it for you.

Many thanks, Nick.

**Comment by karlheyes** [comment]
are you talking about auth url events here or the global "listener_connections" stat.

karl.

**Comment by nickdtodd** [comment]
The stats that I refer to are the ones that we generate ourselves from connections and disconnections sent to 
```
<option name="listener_add" value="http://auth.example.org/listener_joined.php"/>
<option name="listener_remove" value="http://myauthserver.com/listener_left.php"/>
```

So during `relay_reset` the `listener_add` is still happening but not the `listener_remove`.

I hope I'm answering your question here.

Thanks, Nick.

**Comment by karlheyes** [comment]
I've identified a case for the lack of trigger for the auth remove on a failed relay. It's basically down to the 404 response route not checking the mountpoint fully.  I've pushed a fix to master to resolve that.

karl.

**Comment by nickdtodd** [comment]
Hi Karl. Sorry for the delay in getting back to you. I've been away over the festive period.

The changes you made have been implemented on our servers during this time but the problem persists. We're still getting numerous connections that never get disconnected.

Thanks, Nick.

**Comment by karlheyes** [comment]
ok, let me know when the error log is available

karl.

**Comment by nickdtodd** [comment]
Hi Karl,

Here is the part of the log that is causing the problem: http://nopaste.linux-dev.org/?920022

As you can see, it's pretty much the same as before. The lines at the end appear to be connections being sent.

I've used nopaste to keep things neat. Should I post in here to keep a record of it?

Many thanks, Nick.

**Comment by karlheyes** [comment]
I'm not seeing anything at level 4 there, nothing about listeners, auth or stats

karl.

**Comment by nickdtodd** [comment]
Hi Karl,

I've managed to replicate this issue locally by turning off the station source and trying to connect to the stream. Here is some of the error log (debug level 4): http://nopaste.linux-dev.org/?921446

There may be some errors in there regarding passwords and admin stuff. That's due to the local environment not being set up completely.

Thanks, Nick.

**Comment by karlheyes** [comment]
Can you confirm which github master build version you are running on (icecast -v or the date taken), the initial Dec 20 change had a crash bug if you had stream start/end triggers but should not be an issue if those are not configured.

karl.

**Comment by nickdtodd** [comment]
We're using this version: Icecast 2.4.0-kh3-8-g030b4b1

**Comment by karlheyes** [comment]
ok, the latest master should resolve the key problem here.  It wasn't specifically a relay thing, just a problem with the code path clients took when a 404 response was being returned, the mountpoint name was effectively dropped so the remove could not occur.

karl.

**Comment by nickdtodd** [comment]
Hi Karl,

Many thanks for doing this. I deployed the changes yesterday and so far the results look very promising.

I'll report back after a few more days testing and then hopefully close this issue.

Many thanks again,

Nick.

**Comment by nickdtodd** [comment]
After a few days of monitoring it looks like this can be closed. Thanks!
